# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 98fea3b58f2ba5d9883f8d4da80cb9945f024efa195e3a2124ed92fb015de50861f98d64eff05ea36f2726882d8d3ed0bcef0eb7421c8ba5ba506ac1cc66a444

test:
  secret_key_base: 34e6978afa0f2994df7899fb737662b8b2bea1b8d58985619d3bf564e22ede861426908c8fb10e1367b772e46e0d8864ce1fd717274d7b9276bd40e31468ba52

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
